<?php

/**
 * This is the model base class for the table "tbl_user_patient".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserPatient".
 *
 * Columns in table "tbl_user_patient" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $patient_id
 * @property string $last_updated
 *
 */
abstract class BaseUserPatient extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_user_patient';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserPatient|UserPatients', $n);
	}

	public static function representingColumn() {
		return 'last_updated';
	}

	public function rules() {
		return array(
			array('user_id, patient_id', 'numerical', 'integerOnly'=>true),
			array('last_updated', 'length', 'max'=>200),
			array('user_id, patient_id, last_updated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, patient_id, last_updated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'patient_id' => Yii::t('app', 'Patient'),
			'last_updated' => Yii::t('app', 'Last Updated'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('patient_id', $this->patient_id);
		$criteria->compare('last_updated', $this->last_updated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}