<?php

/**
 * This is the model base class for the table "tbl_result_file".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResultFile".
 *
 * Columns in table "tbl_result_file" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $url
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $result_id
 *
 */
abstract class BaseResultFile extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_result_file';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResultFile|ResultFiles', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('created_at, updated_at, result_id', 'numerical', 'integerOnly'=>true),
			array('url', 'safe'),
			array('url, created_at, updated_at, result_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, url, created_at, updated_at, result_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'url' => Yii::t('app', 'Url'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'result_id' => Yii::t('app', 'Result'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('result_id', $this->result_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}