<?php

/**
 * This is the model base class for the table "tbl_provider_order".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProviderOrder".
 *
 * Columns in table "tbl_provider_order" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $address
 * @property integer $status
 * @property integer $active
 * @property integer $service_id
 * @property integer $user_meboo
 * @property string $requirement
 * @property integer $ward
 * @property integer $province
 * @property integer $district
 * @property integer $created_at
 * @property integer $time_confirm
 * @property integer $time_meet
 *
 */
abstract class BaseProviderOrder extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_provider_order';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProviderOrder|ProviderOrders', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('status, active, service_id, user_meboo, ward, province, district, created_at, time_confirm, time_meet', 'numerical', 'integerOnly'=>true),
			array('name, phone, email, address', 'length', 'max'=>255),
			array('requirement', 'safe'),
			array('name, phone, email, address, status, active, service_id, user_meboo, requirement, ward, province, district, created_at, time_confirm, time_meet', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, phone, email, address, status, active, service_id, user_meboo, requirement, ward, province, district, created_at, time_confirm, time_meet', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'phone' => Yii::t('app', 'Phone'),
			'email' => Yii::t('app', 'Email'),
			'address' => Yii::t('app', 'Address'),
			'status' => Yii::t('app', 'Status'),
			'active' => Yii::t('app', 'Active'),
			'service_id' => Yii::t('app', 'Service'),
			'user_meboo' => Yii::t('app', 'User Meboo'),
			'requirement' => Yii::t('app', 'Requirement'),
			'ward' => Yii::t('app', 'Ward'),
			'province' => Yii::t('app', 'Province'),
			'district' => Yii::t('app', 'District'),
			'created_at' => Yii::t('app', 'Created At'),
			'time_confirm' => Yii::t('app', 'Time Confirm'),
			'time_meet' => Yii::t('app', 'Time Meet'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('active', $this->active);
		$criteria->compare('service_id', $this->service_id);
		$criteria->compare('user_meboo', $this->user_meboo);
		$criteria->compare('requirement', $this->requirement, true);
		$criteria->compare('ward', $this->ward);
		$criteria->compare('province', $this->province);
		$criteria->compare('district', $this->district);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('time_confirm', $this->time_confirm);
		$criteria->compare('time_meet', $this->time_meet);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}