<?php

/**
 * This is the model base class for the table "tbl_drug_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DrugType".
 *
 * Columns in table "tbl_drug_type" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $link
 *
 */
abstract class BaseDrugType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_drug_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DrugType|DrugTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('link', 'length', 'max'=>255),
			array('name', 'safe'),
			array('name, link', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, link', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'link' => Yii::t('app', 'Link'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('link', $this->link, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}