<?php

/**
 * This is the model base class for the table "tbl_result_medlatec".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResultMedlatec".
 *
 * Columns in table "tbl_result_medlatec" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $patient_name
 * @property integer $service
 * @property string $time
 * @property string $doctor
 * @property string $diagnose
 * @property string $file
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $order_id
 *
 */
abstract class BaseResultMedlatec extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_result_medlatec';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResultMedlatec|ResultMedlatecs', $n);
	}

	public static function representingColumn() {
		return 'patient_name';
	}

	public function rules() {
		return array(
			array('service, status, created_at, updated_at, order_id', 'numerical', 'integerOnly'=>true),
			array('patient_name, time, doctor', 'length', 'max'=>255),
			array('diagnose, file', 'safe'),
			array('patient_name, service, time, doctor, diagnose, file, status, created_at, updated_at, order_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, patient_name, service, time, doctor, diagnose, file, status, created_at, updated_at, order_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'patient_name' => Yii::t('app', 'Patient Name'),
			'service' => Yii::t('app', 'Service'),
			'time' => Yii::t('app', 'Time'),
			'doctor' => Yii::t('app', 'Doctor'),
			'diagnose' => Yii::t('app', 'Diagnose'),
			'file' => Yii::t('app', 'File'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'order_id' => Yii::t('app', 'Order'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('patient_name', $this->patient_name, true);
		$criteria->compare('service', $this->service);
		$criteria->compare('time', $this->time, true);
		$criteria->compare('doctor', $this->doctor, true);
		$criteria->compare('diagnose', $this->diagnose, true);
		$criteria->compare('file', $this->file, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('order_id', $this->order_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}