<?php

/**
 * This is the model base class for the table "tbl_review".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Review".
 *
 * Columns in table "tbl_review" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $object_id
 * @property integer $object_type
 * @property integer $user_id
 * @property string $review
 * @property integer $time
 * @property integer $rate
 *
 */
abstract class BaseReview extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_review';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Review|Reviews', $n);
	}

	public static function representingColumn() {
		return 'review';
	}

	public function rules() {
		return array(
			array('object_id, object_type, user_id, time, rate', 'numerical', 'integerOnly'=>true),
			array('review', 'safe'),
			array('object_id, object_type, user_id, review, time, rate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, object_id, object_type, user_id, review, time, rate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'object_id' => Yii::t('app', 'Object'),
			'object_type' => Yii::t('app', 'Object Type'),
			'user_id' => Yii::t('app', 'User'),
			'review' => Yii::t('app', 'Review'),
			'time' => Yii::t('app', 'Time'),
			'rate' => Yii::t('app', 'Rate'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('object_id', $this->object_id);
		$criteria->compare('object_type', $this->object_type);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('review', $this->review, true);
		$criteria->compare('time', $this->time);
		$criteria->compare('rate', $this->rate);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}