<?php

/**
 * This is the model base class for the table "tbl_app_db_ver".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AppDbVer".
 *
 * Columns in table "tbl_app_db_ver" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $app_ver
 * @property integer $db_ver
 * @property string $change_log
 * @property integer $min_ver
 *
 */
abstract class BaseAppDbVer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_app_db_ver';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AppDbVer|AppDbVers', $n);
	}

	public static function representingColumn() {
		return 'change_log';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, app_ver, db_ver, min_ver', 'numerical', 'integerOnly'=>true),
			array('change_log', 'safe'),
			array('app_ver, db_ver, change_log, min_ver', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, app_ver, db_ver, change_log, min_ver', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'app_ver' => Yii::t('app', 'App Ver'),
			'db_ver' => Yii::t('app', 'Db Ver'),
			'change_log' => Yii::t('app', 'Change Log'),
			'min_ver' => Yii::t('app', 'Min Ver'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('app_ver', $this->app_ver);
		$criteria->compare('db_ver', $this->db_ver);
		$criteria->compare('change_log', $this->change_log, true);
		$criteria->compare('min_ver', $this->min_ver);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}