<?php

/**
 * This is the model base class for the table "tbl_history_remind".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HistoryRemind".
 *
 * Columns in table "tbl_history_remind" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $remind_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 * @property integer $original_time
 * @property integer $taken_time
 *
 */
abstract class BaseHistoryRemind extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_history_remind';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HistoryRemind|HistoryReminds', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('remind_id, created_at, updated_at, status, original_time, taken_time', 'numerical', 'integerOnly'=>true),
			array('remind_id, created_at, updated_at, status, original_time, taken_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, remind_id, created_at, updated_at, status, original_time, taken_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'remind_id' => Yii::t('app', 'Remind'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'original_time' => Yii::t('app', 'Original Time'),
			'taken_time' => Yii::t('app', 'Taken Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('remind_id', $this->remind_id);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('status', $this->status);
		$criteria->compare('original_time', $this->original_time);
		$criteria->compare('taken_time', $this->taken_time);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}