<?php

/**
 * This is the model base class for the table "tbl_service_medlatec".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ServiceMedlatec".
 *
 * Columns in table "tbl_service_medlatec" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $service_name
 * @property string $service_price
 * @property string $favorable
 * @property string $description
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $service_price_after
 * @property string $relative_favorable
 * @property string $absolute_favorable
 * @property string $condition
 *
 */
abstract class BaseServiceMedlatec extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_service_medlatec';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ServiceMedlatec|ServiceMedlatecs', $n);
	}

	public static function representingColumn() {
		return 'service_name';
	}

	public function rules() {
		return array(
			array('status, created_at, updated_at', 'numerical', 'integerOnly'=>true),
			array('service_name, service_price, favorable, description, service_price_after, relative_favorable, absolute_favorable, condition', 'safe'),
			array('service_name, service_price, favorable, description, status, created_at, updated_at, service_price_after, relative_favorable, absolute_favorable, condition', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, service_name, service_price, favorable, description, status, created_at, updated_at, service_price_after, relative_favorable, absolute_favorable, condition', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'service_name' => Yii::t('app', 'Service Name'),
			'service_price' => Yii::t('app', 'Service Price'),
			'favorable' => Yii::t('app', 'Favorable'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'service_price_after' => Yii::t('app', 'Service Price After'),
			'relative_favorable' => Yii::t('app', 'Relative Favorable'),
			'absolute_favorable' => Yii::t('app', 'Absolute Favorable'),
			'condition' => Yii::t('app', 'Condition'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('service_name', $this->service_name, true);
		$criteria->compare('service_price', $this->service_price, true);
		$criteria->compare('favorable', $this->favorable, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('service_price_after', $this->service_price_after, true);
		$criteria->compare('relative_favorable', $this->relative_favorable, true);
		$criteria->compare('absolute_favorable', $this->absolute_favorable, true);
		$criteria->compare('condition', $this->condition, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}