<?php

/**
 * This is the model base class for the table "tbl_patient_sick".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PatientSick".
 *
 * Columns in table "tbl_patient_sick" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $patient_id
 * @property integer $sick_id
 *
 */
abstract class BasePatientSick extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_patient_sick';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PatientSick|PatientSicks', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('patient_id, sick_id', 'numerical', 'integerOnly'=>true),
			array('patient_id, sick_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, patient_id, sick_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'patient_id' => Yii::t('app', 'Patient'),
			'sick_id' => Yii::t('app', 'Sick'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('patient_id', $this->patient_id);
		$criteria->compare('sick_id', $this->sick_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}