<?php

/**
 * This is the model base class for the table "tbl_provider_service".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProviderService".
 *
 * Columns in table "tbl_provider_service" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $service_name
 * @property integer $service_price
 * @property string $service_description
 * @property string $service_adorable
 * @property integer $provider_id
 * @property string $service_image
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 *
 */
abstract class BaseProviderService extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_provider_service';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProviderService|ProviderServices', $n);
	}

	public static function representingColumn() {
		return 'service_name';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, service_price, provider_id, status, created_at, updated_at', 'numerical', 'integerOnly'=>true),
			array('service_name, service_image', 'length', 'max'=>255),
			array('service_description, service_adorable', 'safe'),
			array('service_name, service_price, service_description, service_adorable, provider_id, service_image, status, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, service_name, service_price, service_description, service_adorable, provider_id, service_image, status, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'service_name' => Yii::t('app', 'Service Name'),
			'service_price' => Yii::t('app', 'Service Price'),
			'service_description' => Yii::t('app', 'Service Description'),
			'service_adorable' => Yii::t('app', 'Service Adorable'),
			'provider_id' => Yii::t('app', 'Provider'),
			'service_image' => Yii::t('app', 'Service Image'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('service_name', $this->service_name, true);
		$criteria->compare('service_price', $this->service_price);
		$criteria->compare('service_description', $this->service_description, true);
		$criteria->compare('service_adorable', $this->service_adorable, true);
		$criteria->compare('provider_id', $this->provider_id);
		$criteria->compare('service_image', $this->service_image, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}