<?php

/**
 * This is the model base class for the table "tbl_patient_injection".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PatientInjection".
 *
 * Columns in table "tbl_patient_injection" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $patient_id
 * @property integer $sick_id
 * @property integer $number
 * @property string $inject_day
 * @property integer $done
 * @property string $month
 * @property string $vaccine_name
 * @property string $note
 * @property string $last_updated
 *
 */
abstract class BasePatientInjection extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_patient_injection';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PatientInjection|PatientInjections', $n);
	}

	public static function representingColumn() {
		return 'inject_day';
	}

	public function rules() {
		return array(
			array('patient_id, sick_id, number, done', 'numerical', 'integerOnly'=>true),
			array('inject_day, month, vaccine_name, note', 'length', 'max'=>255),
			array('last_updated', 'length', 'max'=>200),
			array('patient_id, sick_id, number, inject_day, done, month, vaccine_name, note, last_updated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, patient_id, sick_id, number, inject_day, done, month, vaccine_name, note, last_updated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'patient_id' => Yii::t('app', 'Patient'),
			'sick_id' => Yii::t('app', 'Sick'),
			'number' => Yii::t('app', 'Number'),
			'inject_day' => Yii::t('app', 'Inject Day'),
			'done' => Yii::t('app', 'Done'),
			'month' => Yii::t('app', 'Month'),
			'vaccine_name' => Yii::t('app', 'Vaccine Name'),
			'note' => Yii::t('app', 'Note'),
			'last_updated' => Yii::t('app', 'Last Updated'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('patient_id', $this->patient_id);
		$criteria->compare('sick_id', $this->sick_id);
		$criteria->compare('number', $this->number);
		$criteria->compare('inject_day', $this->inject_day, true);
		$criteria->compare('done', $this->done);
		$criteria->compare('month', $this->month, true);
		$criteria->compare('vaccine_name', $this->vaccine_name, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('last_updated', $this->last_updated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}