<?php

/**
 * This is the model base class for the table "tbl_friends".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Friends".
 *
 * Columns in table "tbl_friends" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_1
 * @property integer $user_2
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 *
 */
abstract class BaseFriends extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_friends';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Friends|Friends', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_1, user_2, created_at, updated_at, status', 'numerical', 'integerOnly'=>true),
			array('user_1, user_2, created_at, updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_1, user_2, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_1' => Yii::t('app', 'User 1'),
			'user_2' => Yii::t('app', 'User 2'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_1', $this->user_1);
		$criteria->compare('user_2', $this->user_2);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}