<?php

/**
 * This is the model base class for the table "tbl_injection_scheduler".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InjectionScheduler".
 *
 * Columns in table "tbl_injection_scheduler" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $sick_id
 * @property string $month
 * @property integer $number
 *
 */
abstract class BaseInjectionScheduler extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_injection_scheduler';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InjectionScheduler|InjectionSchedulers', $n);
	}

	public static function representingColumn() {
		return 'month';
	}

	public function rules() {
		return array(
			array('sick_id, number', 'numerical', 'integerOnly'=>true),
			array('month', 'length', 'max'=>255),
			array('sick_id, month, number', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, sick_id, month, number', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sick_id' => Yii::t('app', 'Sick'),
			'month' => Yii::t('app', 'Month'),
			'number' => Yii::t('app', 'Number'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sick_id', $this->sick_id);
		$criteria->compare('month', $this->month, true);
		$criteria->compare('number', $this->number);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}