<?php

/**
 * This is the model base class for the table "tbl_province".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Province".
 *
 * Columns in table "tbl_province" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $province
 *
 */
abstract class BaseProvince extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_province';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Province|Provinces', $n);
	}

	public static function representingColumn() {
		return 'province';
	}

	public function rules() {
		return array(
			array('province', 'safe'),
			array('province', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, province', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'province' => Yii::t('app', 'Province'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('province', $this->province, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}