<?php

/**
 * This is the model base class for the table "tbl_service_medlatec".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ServiceMedlatec".
 *
 * Columns in table "tbl_service_medlatec" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $service_name
 * @property string $service_price
 * @property string $favorable
 * @property string $description
 * @property integer $status
 *
 */
abstract class BaseServiceMedlatec extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_service_medlatec';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ServiceMedlatec|ServiceMedlatecs', $n);
	}

	public static function representingColumn() {
		return 'service_name';
	}

	public function rules() {
		return array(
			array('status', 'numerical', 'integerOnly'=>true),
			array('service_name, service_price, favorable, description', 'safe'),
			array('service_name, service_price, favorable, description, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, service_name, service_price, favorable, description, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'service_name' => Yii::t('app', 'Service Name'),
			'service_price' => Yii::t('app', 'Service Price'),
			'favorable' => Yii::t('app', 'Favorable'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('service_name', $this->service_name, true);
		$criteria->compare('service_price', $this->service_price, true);
		$criteria->compare('favorable', $this->favorable, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}